name: ðŸ“„ Deploy thesis doc on GitHub pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        uses: typst-community/setup-typst@v4
        with:
          typst-version: 0.13.1

      - name: Build PDF
        run: typst compile doc/thesis.typ bin/thesis.pdf

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          # Optional: Only deploy the PDF
          keep_files: false
          # Specify only thesis.pdf
          file_patterns: bin/thesis.pdf
